### PR TITLE
Put quotes around id file in ssh, as could have spaces

### PR DESCRIPTION
**Pull request by mushishi78**

### CODE REVIEW

**Comment by mushishi78** [comment]
I'm going to close this until I get it right......

**Comment by MadRabbit** [comment]
that looks good, but can you make it a single commit PR, please?

**Comment by mushishi78** [comment]
There you go.

**Comment by mushishi78** [comment]
I forgot the specs, hopefully should pass now

**Comment by MadRabbit** [comment]
sweet, thanks!

**Pull request merged**
