### PR TITLE
Refactor of Command#pick_app

### PR DESCRIPTION
**Pull request by ledestin**
Hi there,

I've refactored `Command#pick_app` and explained my reasons in this post: http://rubyclarity.com/2015/07/ninefold-cli-refactoring/

Hope you find it useful.

### CODE REVIEW

**Comment by MadRabbit** [comment]
Hey Dmitry,

Thank you for taking time and improving the code. Although there are some good ideas in your refactoring, i consider the result a quality degradation.

1) it scattered a very simple piece of functionality among four methods. That might look prettier but it is actually harder to support

2) rubyisms for the sake of rubyisms in my view is an antipattern. The world doesnt revolve around ruby. Empty args list + yield is quite nasty for people outside of ruby circles. So are the many? and one? methods

3) the thing is actually broken now, you relied on 'load_apps' method to return the value of the block, which it doesnt. And even if it did it would return the result of "puts" and yield it as an app down the pupes

So overall, it does look better, but it introduces several unnecessary points of failure, one of which actually failed you yourself already

**Comment by ledestin** [comment]
Hey Nikolay,

Thank you for a thoughtful reply.

1) The idea was to make `pick_app` easier to read, also making it easier to find whatever you want to modify. Private methods don't cost anything until you have to modify them.
Do you mind explaining why my version is harder to support?

2) I see, but in this way your code will be optimised for beginners, not for clarity. And isn't it obvious what `apps.many?` does, given that it's likely an array?

3) Tests still pass, though I realise there are no tests for `pick_app`. I would have tested if I had apps on Ninefold.
The result of `puts` is always `nil`, so `yield app if app` takes care of that and `pick_app` would not call passed block in case of no apps found.

In the end, what will be left of my refactoring if I remove rubyisms, method extraction and `yield` duplication?

**Comment by MadRabbit** [comment]
1) I understand your reasoning, but, the problem is that `pick_app` is a simple self-containing piece of functionality which, on the outside of it does just one thing. by splitting it you make a reader to run across the class chasing those bits of information. before you could just read through it and understand what it is from top to bottom. now one will have to read other methods as well. generally your instinct is correct, but in this case it makes the code worse.

2) Beginners are people too. Also, there are other programming languages as well, and not so beginners will be puzzled by rubyisms and turned away. We don't want that. We want it simple and friendly.

3) Generally correct, unless someone overloaded `puts` (like we did in STDIO). Ruby blocks + inner conditions are generally error prone constructions. It relies too much on people being reasonable. What if one of your private methods start to return a wrong thing? what if someone forgot to return a value from the block? It will fail. `block.call smth` is `block.call smth` no matter where you put it.

The problem here is not your refactoring, but that you refactored the wrong thing. For what it worth, you should make the `pickapp` interaction smarter, rather than polluting the generic `Command` class with things it shouldn't manage.

And the other problem is that you didn't test it. Like at all. You did run the unittests, but you didn't test that the code actually works. I know that because there is no apps on Ninefold anymore. We sunsetted the service months ago :)

**Comment by ledestin** [comment]
1) True, if you really need to read it all for some reason (I don't see what that reason might be though).

2) I understand that, but that's the path leading to `is_many` instead of `many?` :) And `for` loop maybe.

3) True. My answer to that is having tests.

Um, `Command` was already managing things it shouldn't before my refactoring, so no change to that.

Make `pick_app` interaction smarter? Not sure that would be a refactoring as it would change functionality. I'm interested in improving code quality, not in adding functionality.

And, please don't hold it against me that I didn't test my code because it wasn't possible :) As I mentioned, I don't have any apps on Ninefold, so how could I have tested that?

**Comment by MadRabbit** [comment]
No, its all good. I understand your reasons, and i appreciate that you took the initiative and spend time trying to make the code better (i really do). But, all things considered, i don't see this as an improvement.

**Comment by ledestin** [comment]
Ok then. It was an interesting conversation, was interesting to get to know your point of view. Thank you for that!

I'm closing the PR then.

**Comment by MadRabbit** [comment]
Thanks!

**Pull request closed without merging**
